//! E2E (slice 6): cold start enumerates two assigned tickets and
//! dispatches both as cycles. No webhook is sent; any `cycle_completed`
//! that lands on disk therefore originates from the cold-start path
//! (`Dispatcher::admit_for_cold_start` -> `DispatchMsg::ColdStartCycle`
//! -> `step_once(.., CycleTrigger::ColdStart)`).
//!
//! The trigger value itself is not serialized into a `cycle_started` /
//! `cycle_completed` event today — slice 1 only emits `cycle_completed`
//! and that variant carries `cycle_kind` but not `cycle_trigger`. Unit
//! coverage for `CycleTrigger::ColdStart` flowing through the dispatcher
//! lives in `dispatcher::tests::admit_for_cold_start_runs_first_cycle_with_cold_start_trigger`.
//! This fixture is the e2e companion: it asserts the contractually-visible
//! evidence — `cold_start_completed.cycles_spawned == 2` and a
//! per-ticket `cycle_completed` for each of the two enumerated tickets,
//! with no webhook ever delivered.

use std::net::{SocketAddr, TcpListener};
use std::time::Duration;

use tempfile::TempDir;
use tokio::process::Command;
use tokio::time::sleep;
use wiremock::matchers::{body_string_contains, method};
use wiremock::{Mock, MockServer, ResponseTemplate};

mod support_cold_start;
use support_cold_start::{await_cold_start_completed, await_daemon_ready, issue_node};

#[tokio::test]
async fn cold_start_dispatches_two_tickets_with_cold_start_trigger() {
    let port = TcpListener::bind("127.0.0.1:0")
        .expect("bind ephemeral webhook port")
        .local_addr()
        .expect("local_addr")
        .port();

    let linear = MockServer::start().await;

    // Default-priority viewer matcher. Any POST that is not an `issues(...)`
    // query falls through to this responder.
    Mock::given(method("POST"))
        .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
            "data": {"viewer": {"id": "u1"}}
        })))
        .mount(&linear)
        .await;

    // High-priority issues matcher: cold-start enumerate returns two
    // tickets assigned to `u1` in status `todo`. `body_string_contains`
    // matches the GraphQL operation literal generated by
    // `linear::graphql::build_query_body`.
    Mock::given(method("POST"))
        .and(body_string_contains("issues("))
        .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
            "data": {
                "issues": {
                    "pageInfo": { "hasNextPage": false, "endCursor": null },
                    "nodes": [
                        issue_node("a1", "TEAM-1", "todo", "u1"),
                        issue_node("a2", "TEAM-2", "todo", "u1"),
                    ]
                }
            }
        })))
        .with_priority(1)
        .mount(&linear)
        .await;

    let work = TempDir::new().expect("workspace tempdir");
    let session_root = work.path().join("sessions");
    std::fs::create_dir_all(&session_root).unwrap();

    let wt_root = work.path().join("wts");
    std::fs::create_dir_all(&wt_root).unwrap();

    let workflow_path = work.path().join("WORKFLOW.yaml");
    let workflow_body = r#"
admission:
  assignee: u1
  repos:
    - ghq: github.com/example/repo

rules:
  - when:
      status: todo
    tasks:
      - id: run0
        run: 'true'
      - id: post0
        run: 'printf ''{\"directive\":\"end\",\"outcome\":\"done\"}'''
"#;
    std::fs::write(&workflow_path, workflow_body).unwrap();

    let roki_path = work.path().join("roki.toml");
    let roki_body = format!(
        r#"
[linear]
token = "linear-test-token"

[linear.webhook]
bind = "127.0.0.1"
port = {port}

[default]
cli = "echo"

[engine]
max_iterations = 5
shutdown_window_seconds = 10

[paths]
workflow = "{workflow}"
session_root = "{session_root}"

[log]
"#,
        port = port,
        workflow = workflow_path.display(),
        session_root = session_root.display(),
    );
    std::fs::write(&roki_path, roki_body).unwrap();

    let binary = env!("CARGO_BIN_EXE_roki");
    let mut child = Command::new(binary)
        .arg("run")
        .arg("--config")
        .arg(&roki_path)
        .env("ROKI_LINEAR_GRAPHQL_URL", linear.uri())
        .env("ROKI_GHQ_BASE_OVERRIDE", work.path())
        .env("ROKI_WT_ROOT_OVERRIDE", &wt_root)
        .kill_on_drop(true)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .expect("spawn roki binary");

    let webhook_addr: SocketAddr = ([127, 0, 0, 1], port).into();
    wait_for_listener(webhook_addr).await;

    // cold_start_completed lands BEFORE daemon_ready (runtime.rs steps
    // 10/11). Assert on the report first — it carries the dispatch
    // counts the operator cares about.
    let report = await_cold_start_completed(&session_root).await;
    assert_eq!(report["enumerated"], 2, "report = {report}");
    assert_eq!(report["admitted"], 2, "report = {report}");
    assert_eq!(report["cycles_spawned"], 2, "report = {report}");
    assert_eq!(report["enum_partial"], false, "report = {report}");

    // daemon_ready follows; once it lands the gate is open.
    let _ = await_daemon_ready(&session_root).await;

    // Each cold-start cycle eventually emits `cycle_completed` to the
    // per-ticket events file. No webhook was sent — these cycles can
    // only have come from the cold-start admit path.
    for ticket_id in ["a1", "a2"] {
        let events_path = session_root.join(format!("{ticket_id}.events.jsonl"));
        wait_for_event_count(&events_path, "cycle_completed", 1, Duration::from_secs(20)).await;
    }

    // Clean shutdown. SIGTERM the daemon and wait for exit.
    sigterm_child(&child);
    let status = tokio::time::timeout(Duration::from_secs(15), child.wait())
        .await
        .expect("binary should exit within 15s after SIGTERM")
        .expect("child wait succeeds");
    assert!(
        status.success(),
        "binary should exit 0 after SIGTERM, got {status:?}"
    );
}

async fn wait_for_listener(addr: SocketAddr) {
    for _ in 0..50 {
        if tokio::net::TcpStream::connect(addr).await.is_ok() {
            return;
        }
        sleep(Duration::from_millis(100)).await;
    }
    panic!("webhook listener never came up at {addr}");
}

async fn wait_for_event_count(
    path: &std::path::Path,
    event_kind: &str,
    expected_count: usize,
    timeout: Duration,
) {
    let needle = format!("\"event\":\"{event_kind}\"");
    let deadline = tokio::time::Instant::now() + timeout;
    while tokio::time::Instant::now() < deadline {
        if let Ok(body) = tokio::fs::read_to_string(path).await {
            if body.matches(&needle).count() >= expected_count {
                return;
            }
        }
        sleep(Duration::from_millis(50)).await;
    }
    panic!(
        "timed out waiting for {expected_count} occurrences of {event_kind} in {}",
        path.display()
    );
}

fn sigterm_child(child: &tokio::process::Child) {
    use nix::sys::signal::{Signal, kill};
    use nix::unistd::Pid;
    if let Some(pid) = child.id() {
        let _ = kill(Pid::from_raw(pid as i32), Signal::SIGTERM);
    }
}
